version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: laionpedia_database
    volumes:
      - laionpedia_pg_data:/bitnami/postgresql

volumes:
  laionpedia_pg_data: